### ISSUE TITLE
do you want to merge/pull an alternative version for 2.1 ?

### ISSUE THREAD

**Issue by ijgnd** [Arthur-Milchior/anki-latex-header-footer#1]
https://github.com/ijgnd/anki__batch_change_latex_header_footer/blob/master/src/__init__.py

Instead of relying on the add-on config I prefer to add a checkbox to the latex config dialog even though this means I have to overwrite a function. I'm not sure if it's better than your approach, especially if a user also installs your "Newline in strings in add-ons configurations". I just like my approach better.

On the other hand I'd like to make this code accessible on ankiweb. I don't care how. So if you want to use parts of my code to update your ankiweb listing I'm fine with this - the world doesn't really need to add-ons for this. If you don't like my code I will probably upload it to ankiweb in a few weeks.

As always: Thanks for your great additions to anki(droid).

**Comment by Arthur-Milchior** [comment]
Hi

I love it. I did replace my add-on by yours.
Ideally, I'd love to just let you take care of the add-on, but there is no way to transfer add-ons as far as I know ankiweb. 
I did add you in the readme file.

You're welcome, but honestly, I don't get why you thank me for a code you wrote (which is not related to ankidroid at all)

**Comment by Arthur-Milchior** [comment]
Do you want credit in any way ? I added you to the read me and of course let your name in file header. Don't know whether you usually do more

**Comment by ijgnd** [comment]
It's great that you merged my ideas and I'm happy with the way you already credited me in the python file and the readme.
