### ISSUE TITLE
When You Say Header / Footer

### ISSUE THREAD

**Issue by LimitedCodingSkill** [Arthur-Milchior/anki-latex-header-footer#2]
Hi,

Seems like the instructions are just 4 lines.  I couldn't understand them as I am really a newbie to Anki / coding in general.

`To use:
1) Open the main browser
2) Select "change LaTeX"
3) Enter the LaTeX header
4) Enter the LaTeX footer`

A few questions, please.  

When you say "Header & Footer" what do you mean?  Is this something that is in the code of the cards and not displayed?

What I need is something that could be programmed to auto-repeat visibly across the top of every card.  Something like:

**3.2 Pulmonary System 
Intro**
(Maybe cards 1 ~ 13)

Then

**3.2 Pulmonary System 
1 - Respiration**
(Maybe cards 14 ~ 23)

**3.2 Pulmonary System 
2 - Hemoglobin**
(Maybe Cards 24 ~ 40)

When you say "Header" is that what you mean?  A fixed, visible repeating kind of "title" that shows at the top of every card?

Thanks!

**Comment by Arthur-Milchior** [comment]
This is related to latex. If you don't use latex, this add-on is not for you.

**Comment by LimitedCodingSkill** [comment]
Hi,

I'd be happy to use latex if it can do what I described. :D  Can you explain what you mean when you say Headers & Footers?

**Comment by Arthur-Milchior** [comment]
LaTeX is a system to write mathematics formula mainly. It's not related to your goal. And anyway a quick google search would give you this kind of answer: https://www.overleaf.com/learn/latex/Headers_and_footers

**Comment by LimitedCodingSkill** [comment]
Hi,

You are right about Latex.  Mathematical papers rely on it extensively.  

It can do many things - self-described as “A document preparation system.  LaTeX is a high-quality typesetting system; it includes features designed for the production of technical and scientific documentation.”

One of the key features is the Header & the Footer.  

According to the Header & Footer documentation you shared “If your document is double-sided, for example a book, and you need to customize the header and the footer, the recommended commands in this case are \fancyhead and \fancyfoot with several selectors passed as parameters.”

Then, they provide an illustration: 

![repeating-headers](https://user-images.githubusercontent.com/59731481/72199701-89c0f480-347a-11ea-96aa-29cd45ce8129.png)

Note the red arrows.

Can your plugin apply similar headers and footers to Anki cards?
