### ISSUE TITLE
broken in 2.1.28+ - new code included

### ISSUE THREAD

**Issue by ijgnd** [Arthur-Milchior/anki-latex-header-footer#3]
Apparently it's broken in 2.1.28 or later, see this report in the [anki forum](https://forums.ankiweb.net/t/common-latex-header-for-multiple-note-types/4712/4).

I made some quick changes which after a short test seem to work, see [this commit](https://github.com/ijgnd/anki__batch_change_latex_header_footer/commit/90b31556628ce5a6721987b998d4d15d53568ca7). I think this commit can be improved ...

I forgot to fork your repo first so I can't make a pull request. I guess it's easier to just copy my [`__init__.py`](https://github.com/ijgnd/anki__batch_change_latex_header_footer/blob/master/src/__init__.py) and adjust it.

**Comment by ijgnd** [comment]
I just saw that I have set AGPL as the license and you prefer the regular GPL. I think it's enough to state here that my changes in the recent commit are also licensed under the GPLv3?

**Comment by Arthur-Milchior** [comment]
Do you want to be in charge of this add-on ? I know it is possible to ask DAE to transfer add-on, and since you are the one who created this version (which is better than mine anyway) this would make sens

**Comment by Arthur-Milchior** [comment]
Just tried your file and got the error message

> Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.1 Qt 5.15.1 PyQt 5.15.1
Platform: Linux
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-11-23 01:10:34
Add-ons possibly involved: ⁨LaTeXs Headerfooter edit everywhere⁩

Caught exception:
Traceback (most recent call last):
  File "</usr/local/share/anki/bin/decorator.pyc:decorator-gen-2>", line 2, in onAdvanced
  File "anki/hooks.py", line 638, in decorator_wrapper
  File "anki/hooks.py", line 630, in repl
  File "/home/milchior/.local/share/Anki2/addons21/1863928230/__init__.py", line 48, in onAdvanced
    if apply_to_all.isChecked():
RuntimeError: wrapped C/C++ object of type QCheckBox has been deleted

This occured when I tried to close the "option" window, with your checkbox selected

**Comment by Arthur-Milchior** [comment]
Uploaded. Thanks

**Comment by ijgnd** [comment]
> Do you want to be in charge of this add-on ? 

Not really. I don't care about this add-on - if it's broken on ankiweb for some time: who cares? I don't mind making pull requests if I have new code and I don't mind waiting for a month. 

But if you don't want to upload changes to ankiweb anymore I guess I could take it over, especially since my fix for 2.1.28+ is ugly.
